### ISSUE TITLE
.gitignore file is missing

### ISSUE THREAD

**Issue by npagare** [vimal1994/Popup_RTL#2]
Hi @vimal1994 , @Sivaraman761 ,

I have accepted your invite for collaboration. Will you please confirm my contributor access?

I see that .gitignore file is missing.

I have made few updates that reproduces the issue on iOS around TapGestureRecognizer when TapCount # 2.
But, I am still not able to reproduce the issue of Grid - Column change order when in RTL.

Will you please upload .gitignore file before send a PR for my changes ?

Thank you,
Nilesh

**Comment by Sivaraman761** [comment]
Hi @IoTFier 

we have committed the .gitignore file. And you have contributor access for this repo.

Regards,
Sivaraman S

**Comment by npagare** [comment]
Hi @Sivaraman761 ,

Thank you for adding the .gitignore file.
I have updated its content from the latest version of the VisualStudio.gitignore from the url - https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore

Thank you,
Nilesh
